export const INITIAL_CATEGORIES = [
  "Accesorios",
  "Bisuteria",
  "Ropa",
  "Papeleria",
  "Computacion",
  "Cuidado de la piel",
  "Decoración",
  "Juguete"
];

export const INITIAL_TYPES = {
  "Accesorios": [
    "Bolso",
    "Gafas",
    "Llavero",
    "Monedero",
    "Vinchas",
    "Reloj",
    "Pulsera",
    "Cepillo",
    "Espejo",
    "Diadema",
    "Portalabiales",
    "Pendientes",
    "Billetera",
    "Estuche",
    "Mochila",
    "Delantal",
    "Cordones"
  ],
  "Bisuteria": [
    "Anillo",
    "Arete",
    "Collar",
    "Gargantilla",
    "Pulsera",
    "Aretes",
    "Anillos",
    "Cadena",
    "aretes",
    "Conjunto",
    "Pendientes"
  ],
  "Ropa": [
    "Camiseta"
  ],
  "Papeleria": [
    "Pinturas",
    "Stickers",
    "Libretas",
    "Esferos",
    "Marcadores",
    "Lápiz",
    "Resaltador"
  ],
  "Computacion": [
    "Mouse"
  ],
  "Cuidado de la piel": [
    "Acné"
  ],
  "Decoración": [
    "Adornos"
  ],
  "Juguete": [
    "Jueguete",
    "mu;ecos"
  ]
};

export const INITIAL_PRODUCTS = [
  {
    "id": 1,
    "name": "Bolso tela cubo rosa Hello Kitty",
    "description": "Bolso tela cubo rosa Hello Kitty",
    "price": 8,
    "cost": 3.89,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 2,
    "name": "Bolso tela bandolera Hello Kitty",
    "description": "Bolso tela bandolera Hello Kitty",
    "price": 10,
    "cost": 5.6,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 3,
    "name": "Bolso cuerina Mensajerìa Hello Kitty",
    "description": "Bolso cuerina Mensajerìa Hello Kitty",
    "price": 10,
    "cost": 4.8,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 4,
    "name": "Bolso impermeable bandolera Hello Kitty",
    "description": "Bolso impermeable bandolera Hello Kitty",
    "price": 12,
    "cost": 7.88,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 5,
    "name": "Mochila Hello Kitty",
    "description": "Mochila Hello Kitty",
    "price": 12,
    "cost": 8.03,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 6,
    "name": "Gafas Niña Hello Kitty",
    "description": "Gafas Niña Hello Kitty",
    "price": 4,
    "cost": 1.78,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Gafas",
    "images": [],
    "image": null
  },
  {
    "id": 7,
    "name": "Anillo Mounstro",
    "description": "Anillo Mounstro",
    "price": 1,
    "cost": 7.26,
    "stock": 20,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Anillo",
    "images": [],
    "image": null
  },
  {
    "id": 8,
    "name": "Anillo resina",
    "description": "Anillo resina",
    "price": 1,
    "cost": 2.51,
    "stock": 10,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Anillo",
    "images": [],
    "image": null
  },
  {
    "id": 9,
    "name": "Anillo Metal Piedras Rosadas",
    "description": "Anillo Metal Piedras Rosadas",
    "price": 1,
    "cost": 3.65,
    "stock": 10,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Anillo",
    "images": [],
    "image": null
  },
  {
    "id": 10,
    "name": "Aretes Gato Negro",
    "description": "Aretes Gato Negro",
    "price": 5,
    "cost": 2.78,
    "stock": 2,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Arete",
    "images": [],
    "image": null
  },
  {
    "id": 11,
    "name": "Relicario Hello Kitty",
    "description": "Relicario Hello Kitty",
    "price": 4,
    "cost": 1.91,
    "stock": 2,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Collar",
    "images": [],
    "image": null
  },
  {
    "id": 12,
    "name": "Gargantillas",
    "description": "Gargantillas",
    "price": 0.5,
    "cost": 1.62,
    "stock": 12,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Gargantilla",
    "images": [],
    "image": null
  },
  {
    "id": 13,
    "name": "Pulseras niña",
    "description": "Pulseras niña",
    "price": 2,
    "cost": 5.55,
    "stock": 10,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Pulsera",
    "images": [],
    "image": null
  },
  {
    "id": 14,
    "name": "Pulsera Hello Kitty",
    "description": "Pulsera Hello Kitty",
    "price": 3,
    "cost": 0.77,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Pulsera",
    "images": [],
    "image": null
  },
  {
    "id": 15,
    "name": "Camiseta Estampado Hello Kitty",
    "description": "Camiseta Estampado Hello Kitty",
    "price": 12,
    "cost": 5.88,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Ropa",
    "subcategory": "Camiseta",
    "images": [],
    "image": null
  },
  {
    "id": 16,
    "name": "Aretes Gato Abrazado con Cola (plata)",
    "description": "Aretes Gato Abrazado con Cola (plata)",
    "price": 6.5,
    "cost": 3.44,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Aretes",
    "images": [],
    "image": null
  },
  {
    "id": 17,
    "name": "Aretes largos de Alas",
    "description": "Aretes largos de Alas",
    "price": 3.5,
    "cost": 1.9,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Aretes",
    "images": [],
    "image": null
  },
  {
    "id": 18,
    "name": "Aretes Tulipan Negro",
    "description": "Aretes Tulipan Negro",
    "price": 3.5,
    "cost": 1.85,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Aretes",
    "images": [],
    "image": null
  },
  {
    "id": 19,
    "name": "Aretes Conejo Peluche",
    "description": "Aretes Conejo Peluche",
    "price": 3.5,
    "cost": 1.47,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Aretes",
    "images": [],
    "image": null
  },
  {
    "id": 20,
    "name": "Aretes Perrito Peluche",
    "description": "Aretes Perrito Peluche",
    "price": 3.5,
    "cost": 1.68,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Aretes",
    "images": [],
    "image": null
  },
  {
    "id": 21,
    "name": "Aretes Hello Kitty con cuerpo",
    "description": "Aretes Hello Kitty con cuerpo",
    "price": 3,
    "cost": 1.33,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Aretes",
    "images": [],
    "image": null
  },
  {
    "id": 22,
    "name": "Aretes Pequeños Sanrio",
    "description": "Aretes Pequeños Sanrio",
    "price": 0.75,
    "cost": 1.5,
    "stock": 6,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Aretes",
    "images": [],
    "image": null
  },
  {
    "id": 23,
    "name": "Aretes Hello Kitty (plata)",
    "description": "Aretes Hello Kitty (plata)",
    "price": 4.5,
    "cost": 2.6,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Aretes",
    "images": [],
    "image": null
  },
  {
    "id": 24,
    "name": "Bolso negro Hello Kitty",
    "description": "Bolso negro Hello Kitty",
    "price": 8,
    "cost": 3.99,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 25,
    "name": "Mochila Hello Kitty con muñequito",
    "description": "Mochila Hello Kitty con muñequito",
    "price": 10,
    "cost": 6.85,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 26,
    "name": "Llavero Sanrio para bolso",
    "description": "Llavero Sanrio para bolso",
    "price": 1,
    "cost": 2.77,
    "stock": 6,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Llavero",
    "images": [],
    "image": null
  },
  {
    "id": 27,
    "name": "Gargantilla de acero",
    "description": "Gargantilla de acero",
    "price": 2,
    "cost": 0.77,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Gargantilla",
    "images": [],
    "image": null
  },
  {
    "id": 28,
    "name": "Cosmetiquera Hello Kitty rosa",
    "description": "Cosmetiquera Hello Kitty rosa",
    "price": 6,
    "cost": 2.77,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 29,
    "name": "Cosmetiquera Hello Kitty acolchonada",
    "description": "Cosmetiquera Hello Kitty acolchonada",
    "price": 7,
    "cost": 4.43,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 30,
    "name": "Cosmetiquera Hello Kitty negra sencilla",
    "description": "Cosmetiquera Hello Kitty negra sencilla",
    "price": 4,
    "cost": 2.77,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 31,
    "name": "Pulsera Kuromi ajustable",
    "description": "Pulsera Kuromi ajustable",
    "price": 2,
    "cost": 0.85,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Pulsera",
    "images": [],
    "image": null
  },
  {
    "id": 32,
    "name": "Pulsera Kuromi elastica",
    "description": "Pulsera Kuromi elastica",
    "price": 3,
    "cost": 1.12,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Pulsera",
    "images": [],
    "image": null
  },
  {
    "id": 33,
    "name": "Monedero Hello Kitty",
    "description": "Monedero Hello Kitty",
    "price": 3,
    "cost": 1.77,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Monedero",
    "images": [],
    "image": null
  },
  {
    "id": 34,
    "name": "Llavero Hello Kitty y Flor",
    "description": "Llavero Hello Kitty y Flor",
    "price": 2.5,
    "cost": 1.21,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Llavero",
    "images": [],
    "image": null
  },
  {
    "id": 35,
    "name": "Lonchera térmica Hello Kitty",
    "description": "Lonchera térmica Hello Kitty",
    "price": 7,
    "cost": 4.43,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 36,
    "name": "Collar Kuromi",
    "description": "Collar Kuromi",
    "price": 4,
    "cost": 1.78,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Collar",
    "images": [],
    "image": null
  },
  {
    "id": 37,
    "name": "Bolso Hello Kitty con cosmetiquera",
    "description": "Bolso Hello Kitty con cosmetiquera",
    "price": 10,
    "cost": 4.83,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 38,
    "name": "Pinturas multicolor",
    "description": "Pinturas multicolor",
    "price": 0.5,
    "cost": 3.26,
    "stock": 12,
    "tax": 0,
    "discount": 0,
    "category": "Papeleria",
    "subcategory": "Pinturas",
    "images": [],
    "image": null
  },
  {
    "id": 39,
    "name": "Mouse tipo carrito Rosa",
    "description": "Mouse tipo carrito Rosa",
    "price": 7,
    "cost": 4.35,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Computacion",
    "subcategory": "Mouse",
    "images": [],
    "image": null
  },
  {
    "id": 40,
    "name": "Parches para acné tipo estrella",
    "description": "Parches para acné tipo estrella",
    "price": 0.5,
    "cost": 1.75,
    "stock": 18,
    "tax": 0,
    "discount": 0,
    "category": "Cuidado de la piel",
    "subcategory": "Acné",
    "images": [],
    "image": null
  },
  {
    "id": 41,
    "name": "Stickers Melody lámina pequeña",
    "description": "Stickers Melody lámina pequeña",
    "price": 0.15,
    "cost": 1.5,
    "stock": 40,
    "tax": 0,
    "discount": 0,
    "category": "Papeleria",
    "subcategory": "Stickers",
    "images": [],
    "image": null
  },
  {
    "id": 42,
    "name": "Aretes animales mordiendo",
    "description": "Aretes animales mordiendo",
    "price": 2.5,
    "cost": 6.44,
    "stock": 7,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Aretes",
    "images": [],
    "image": null
  },
  {
    "id": 43,
    "name": "Mini libreta llavero",
    "description": "Mini libreta llavero",
    "price": 0.75,
    "cost": 1.1,
    "stock": 2,
    "tax": 0,
    "discount": 0,
    "category": "Papeleria",
    "subcategory": "Libretas",
    "images": [],
    "image": null
  },
  {
    "id": 44,
    "name": "Mini libreta llavero",
    "description": "Mini libreta llavero",
    "price": 1,
    "cost": 3.92,
    "stock": 6,
    "tax": 0,
    "discount": 0,
    "category": "Papeleria",
    "subcategory": "Libretas",
    "images": [],
    "image": null
  },
  {
    "id": 45,
    "name": "Pulsera de cordón con corazón",
    "description": "Pulsera de cordón con corazón",
    "price": 0.5,
    "cost": 2.8,
    "stock": 24,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Pulsera",
    "images": [],
    "image": null
  },
  {
    "id": 46,
    "name": "Bolso bandolera negro Hello Kitty",
    "description": "Bolso bandolera negro Hello Kitty",
    "price": 10,
    "cost": 6.35,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 47,
    "name": "Llavero peluche Hello Kitty cafè",
    "description": "Llavero peluche Hello Kitty cafè",
    "price": 3,
    "cost": 1.89,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Llavero",
    "images": [],
    "image": null
  },
  {
    "id": 48,
    "name": "Llavero peluche Hello Kitty pequeño",
    "description": "Llavero peluche Hello Kitty pequeño",
    "price": 3,
    "cost": 1.51,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Llavero",
    "images": [],
    "image": null
  },
  {
    "id": 49,
    "name": "Llavero peluche cinnamon",
    "description": "Llavero peluche cinnamon",
    "price": 3,
    "cost": 1.4,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Llavero",
    "images": [],
    "image": null
  },
  {
    "id": 50,
    "name": "Llavero peluche Hello Kitty lazo rojo",
    "description": "Llavero peluche Hello Kitty lazo rojo",
    "price": 4,
    "cost": 2.26,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Llavero",
    "images": [],
    "image": null
  },
  {
    "id": 51,
    "name": "Llavero peluche Hello Kitty oso blanco",
    "description": "Llavero peluche Hello Kitty oso blanco",
    "price": 3,
    "cost": 1.67,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Llavero",
    "images": [],
    "image": null
  },
  {
    "id": 52,
    "name": "Aretes mariposa",
    "description": "Aretes mariposa",
    "price": 2.5,
    "cost": 0.86,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Aretes",
    "images": [],
    "image": null
  },
  {
    "id": 53,
    "name": "Aretes flor grandes",
    "description": "Aretes flor grandes",
    "price": 3.5,
    "cost": 1.55,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Aretes",
    "images": [],
    "image": null
  },
  {
    "id": 54,
    "name": "Aretes largos de estrella y luna",
    "description": "Aretes largos de estrella y luna",
    "price": 3.5,
    "cost": 1.37,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Aretes",
    "images": [],
    "image": null
  },
  {
    "id": 55,
    "name": "Aretes estrella largos",
    "description": "Aretes estrella largos",
    "price": 3.5,
    "cost": 1.69,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Aretes",
    "images": [],
    "image": null
  },
  {
    "id": 56,
    "name": "Vinchas para cabello flores",
    "description": "Vinchas para cabello flores",
    "price": 3,
    "cost": 1.57,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Vinchas",
    "images": [],
    "image": null
  },
  {
    "id": 57,
    "name": "Aretes de gato",
    "description": "Aretes de gato",
    "price": 1.25,
    "cost": 1.97,
    "stock": 4,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Aretes",
    "images": [],
    "image": null
  },
  {
    "id": 58,
    "name": "Pulsera ajustable hoja",
    "description": "Pulsera ajustable hoja",
    "price": 5,
    "cost": 2.8,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Pulsera",
    "images": [],
    "image": null
  },
  {
    "id": 59,
    "name": "Anillos ajustables",
    "description": "Anillos ajustables",
    "price": 2.5,
    "cost": 3.72,
    "stock": 5,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Anillos",
    "images": [],
    "image": null
  },
  {
    "id": 60,
    "name": "Pulseras acero inoxidable",
    "description": "Pulseras acero inoxidable",
    "price": 1,
    "cost": 2.04,
    "stock": 5,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Pulsera",
    "images": [],
    "image": null
  },
  {
    "id": 61,
    "name": "Bolso lona Hello Kitty lazo rojo",
    "description": "Bolso lona Hello Kitty lazo rojo",
    "price": 7,
    "cost": 4.68,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 62,
    "name": "Bolso de viaje rosado grande",
    "description": "Bolso de viaje rosado grande",
    "price": 20,
    "cost": 15.61,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 63,
    "name": "Bolso de lona Hello Kitty rosado",
    "description": "Bolso de lona Hello Kitty rosado",
    "price": 7,
    "cost": 4.26,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 64,
    "name": "Bolso de lona Hello Kitty rojo",
    "description": "Bolso de lona Hello Kitty rojo",
    "price": 7,
    "cost": 4.84,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 65,
    "name": "Bolso de lona Hello Kitty animal print",
    "description": "Bolso de lona Hello Kitty animal print",
    "price": 8,
    "cost": 4.94,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 66,
    "name": "Monedero Hello Kitty con sombrero",
    "description": "Monedero Hello Kitty con sombrero",
    "price": 3,
    "cost": 1.5,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Monedero",
    "images": [],
    "image": null
  },
  {
    "id": 67,
    "name": "Cosmetiquera blanca Hello Kitty",
    "description": "Cosmetiquera blanca Hello Kitty",
    "price": 5,
    "cost": 2.8,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 68,
    "name": "Bolso de lona rosado Hello Kitty",
    "description": "Bolso de lona rosado Hello Kitty",
    "price": 8,
    "cost": 5.99,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 69,
    "name": "Anillos ajustables de mounstro",
    "description": "Anillos ajustables de mounstro",
    "price": 1,
    "cost": 4.42,
    "stock": 10,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Anillos",
    "images": [],
    "image": null
  },
  {
    "id": 70,
    "name": "Bolso negro grande Hello Kitty",
    "description": "Bolso negro grande Hello Kitty",
    "price": 12,
    "cost": 6.98,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 71,
    "name": "Cosmetiquera rosada Hello Kitty",
    "description": "Cosmetiquera rosada Hello Kitty",
    "price": 6,
    "cost": 2.35,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 72,
    "name": "Bolso de tela negra con brillos Hello Kitty",
    "description": "Bolso de tela negra con brillos Hello Kitty",
    "price": 7,
    "cost": 3.96,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 73,
    "name": "Laveros peluche pequeño Hello Kitty",
    "description": "Laveros peluche pequeño Hello Kitty",
    "price": 2,
    "cost": 3.46,
    "stock": 5,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Llavero",
    "images": [],
    "image": null
  },
  {
    "id": 74,
    "name": "Llaveros metàlicos Hello Kitty",
    "description": "Llaveros metàlicos Hello Kitty",
    "price": 2.5,
    "cost": 4.32,
    "stock": 6,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Llavero",
    "images": [],
    "image": null
  },
  {
    "id": 75,
    "name": "Bolso pequeño blanco con negro Hello Kitty",
    "description": "Bolso pequeño blanco con negro Hello Kitty",
    "price": 13,
    "cost": 6.69,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 76,
    "name": "Adorno para carro Hello Kitty",
    "description": "Adorno para carro Hello Kitty",
    "price": 1,
    "cost": 1.96,
    "stock": 5,
    "tax": 0,
    "discount": 0,
    "category": "Decoración",
    "subcategory": "Adornos",
    "images": [],
    "image": null
  },
  {
    "id": 77,
    "name": "Llaveros sanrio Hello Kitty",
    "description": "Llaveros sanrio Hello Kitty",
    "price": 1,
    "cost": 1.53,
    "stock": 6,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Llavero",
    "images": [],
    "image": null
  },
  {
    "id": 78,
    "name": "Llaveros Sario Personajes Hello Kitty",
    "description": "Llaveros Sario Personajes Hello Kitty",
    "price": 1,
    "cost": 2.28,
    "stock": 6,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Llavero",
    "images": [],
    "image": null
  },
  {
    "id": 79,
    "name": "Dinosaurios",
    "description": "Dinosaurios",
    "price": 1.5,
    "cost": 15.83,
    "stock": 20,
    "tax": 0,
    "discount": 0,
    "category": "Juguete",
    "subcategory": "Jueguete",
    "images": [],
    "image": null
  },
  {
    "id": 80,
    "name": "Reloj cuarzo Hello Kitty",
    "description": "Reloj cuarzo Hello Kitty",
    "price": 6,
    "cost": 2.61,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Reloj",
    "images": [],
    "image": null
  },
  {
    "id": 81,
    "name": "Conjunto pulsera y cadena Hello Kitty",
    "description": "Conjunto pulsera y cadena Hello Kitty",
    "price": 5,
    "cost": 2.05,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Pulsera",
    "images": [],
    "image": null
  },
  {
    "id": 82,
    "name": "Reloj Sanrio Plateado Hello Kitty",
    "description": "Reloj Sanrio Plateado Hello Kitty",
    "price": 10,
    "cost": 3.21,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Reloj",
    "images": [],
    "image": null
  },
  {
    "id": 83,
    "name": "Reloj dorado Hello Kitty",
    "description": "Reloj dorado Hello Kitty",
    "price": 10,
    "cost": 3.68,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Reloj",
    "images": [],
    "image": null
  },
  {
    "id": 84,
    "name": "Anillo dragón",
    "description": "Anillo dragón",
    "price": 3,
    "cost": 0.97,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Anillo",
    "images": [],
    "image": null
  },
  {
    "id": 85,
    "name": "Reloj pulsera Hello Kitty",
    "description": "Reloj pulsera Hello Kitty",
    "price": 10,
    "cost": 4.44,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Reloj",
    "images": [],
    "image": null
  },
  {
    "id": 86,
    "name": "Reloj pulsera rosada Hello Kitty",
    "description": "Reloj pulsera rosada Hello Kitty",
    "price": 5,
    "cost": 1.83,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Reloj",
    "images": [],
    "image": null
  },
  {
    "id": 87,
    "name": "Reloj negro hombre",
    "description": "Reloj negro hombre",
    "price": 4,
    "cost": 1.79,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Reloj",
    "images": [],
    "image": null
  },
  {
    "id": 88,
    "name": "Monedero blanco Hello Kitty",
    "description": "Monedero blanco Hello Kitty",
    "price": 3,
    "cost": 1.67,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Monedero",
    "images": [],
    "image": null
  },
  {
    "id": 89,
    "name": "Bolso de lona Mickey Mouse",
    "description": "Bolso de lona Mickey Mouse",
    "price": 7,
    "cost": 3.72,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 90,
    "name": "Porta tarjetas Hello Kitty",
    "description": "Porta tarjetas Hello Kitty",
    "price": 3,
    "cost": 1.52,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Monedero",
    "images": [],
    "image": null
  },
  {
    "id": 91,
    "name": "Monedero con broche Hello Kitty",
    "description": "Monedero con broche Hello Kitty",
    "price": 3,
    "cost": 1.03,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Monedero",
    "images": [],
    "image": null
  },
  {
    "id": 92,
    "name": "Bolso de lona rosado con blanco Hello Kitty",
    "description": "Bolso de lona rosado con blanco Hello Kitty",
    "price": 7,
    "cost": 3.71,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 93,
    "name": "Pulsera Hello Kitty",
    "description": "Pulsera Hello Kitty",
    "price": 3,
    "cost": 0.74,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Pulsera",
    "images": [],
    "image": null
  },
  {
    "id": 94,
    "name": "Bolso Melody",
    "description": "Bolso Melody",
    "price": 8,
    "cost": 3.7,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 95,
    "name": "Conjunto pulsera y cadena Hello Kitty",
    "description": "Conjunto pulsera y cadena Hello Kitty",
    "price": 5,
    "cost": 2.46,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Pulsera",
    "images": [],
    "image": null
  },
  {
    "id": 96,
    "name": "Cadenas Hello Kitty",
    "description": "Cadenas Hello Kitty",
    "price": 1.5,
    "cost": 2.06,
    "stock": 5,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Cadena",
    "images": [],
    "image": null
  },
  {
    "id": 97,
    "name": "Bolso de pana Hello Kitty",
    "description": "Bolso de pana Hello Kitty",
    "price": 7,
    "cost": 3.59,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 98,
    "name": "Cepillo de cabello Hello Kitty",
    "description": "Cepillo de cabello Hello Kitty",
    "price": 4,
    "cost": 2.05,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Cepillo",
    "images": [],
    "image": null
  },
  {
    "id": 99,
    "name": "Llaveros Hello Kitty",
    "description": "Llaveros Hello Kitty",
    "price": 1,
    "cost": 1.48,
    "stock": 6,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Llavero",
    "images": [],
    "image": null
  },
  {
    "id": 100,
    "name": "Bolso pequeño rosado Hello Kitty",
    "description": "Bolso pequeño rosado Hello Kitty",
    "price": 6,
    "cost": 2.77,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 101,
    "name": "Pulsera de hilo Hello Kitty",
    "description": "Pulsera de hilo Hello Kitty",
    "price": 2,
    "cost": 0.7,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Pulsera",
    "images": [],
    "image": null
  },
  {
    "id": 102,
    "name": "Porta toallas sanitarias Hello Kitty",
    "description": "Porta toallas sanitarias Hello Kitty",
    "price": 3,
    "cost": 1.71,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 103,
    "name": "Cartuchera negra Hello Kitty",
    "description": "Cartuchera negra Hello Kitty",
    "price": 4,
    "cost": 1.99,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 104,
    "name": "Bolso de mano Hello Kitty",
    "description": "Bolso de mano Hello Kitty",
    "price": 5,
    "cost": 2.17,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 105,
    "name": "Cadena Hello Kitty con flor",
    "description": "Cadena Hello Kitty con flor",
    "price": 2.5,
    "cost": 1.13,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Cadena",
    "images": [],
    "image": null
  },
  {
    "id": 106,
    "name": "Cadenas Cinnamon",
    "description": "Cadenas Cinnamon",
    "price": 1,
    "cost": 1.6,
    "stock": 4,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Cadena",
    "images": [],
    "image": null
  },
  {
    "id": 107,
    "name": "Reloj despertador Hello Kitty",
    "description": "Reloj despertador Hello Kitty",
    "price": 5,
    "cost": 2.95,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Reloj",
    "images": [],
    "image": null
  },
  {
    "id": 108,
    "name": "Bolso, mochila Hello Kitty",
    "description": "Bolso, mochila Hello Kitty",
    "price": 12,
    "cost": 6.27,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 109,
    "name": "Bolso negro con lazo rojo Hello Kitty",
    "description": "Bolso negro con lazo rojo Hello Kitty",
    "price": 15,
    "cost": 11.84,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 110,
    "name": "Stickers Sanrio lámina grande",
    "description": "Stickers Sanrio lámina grande",
    "price": 0.4,
    "cost": 2.11,
    "stock": 16,
    "tax": 0,
    "discount": 0,
    "category": "Papeleria",
    "subcategory": "Stickers",
    "images": [],
    "image": null
  },
  {
    "id": 111,
    "name": "Esferos tipo sello, flores",
    "description": "Esferos tipo sello, flores",
    "price": 1.25,
    "cost": 3.71,
    "stock": 6,
    "tax": 0,
    "discount": 0,
    "category": "Papeleria",
    "subcategory": "Esferos",
    "images": [],
    "image": null
  },
  {
    "id": 112,
    "name": "Marcadores dorado y plateado",
    "description": "Marcadores dorado y plateado",
    "price": 1.5,
    "cost": 2.16,
    "stock": 2,
    "tax": 0,
    "discount": 0,
    "category": "Papeleria",
    "subcategory": "Marcadores",
    "images": [],
    "image": null
  },
  {
    "id": 113,
    "name": "Lapices arcoiris",
    "description": "Lapices arcoiris",
    "price": 0.5,
    "cost": 6.62,
    "stock": 24,
    "tax": 0,
    "discount": 0,
    "category": "Papeleria",
    "subcategory": "Pinturas",
    "images": [],
    "image": null
  },
  {
    "id": 114,
    "name": "Lapices eternos de  colores con respuestos",
    "description": "Lapices eternos de  colores con respuestos",
    "price": 1.25,
    "cost": 3.36,
    "stock": 12,
    "tax": 0,
    "discount": 0,
    "category": "Papeleria",
    "subcategory": "Lápiz",
    "images": [],
    "image": null
  },
  {
    "id": 115,
    "name": "Aretes fantasma",
    "description": "Aretes fantasma",
    "price": 4,
    "cost": 2.95,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Aretes",
    "images": [],
    "image": null
  },
  {
    "id": 116,
    "name": "Aretes animales mordiendo",
    "description": "Aretes animales mordiendo",
    "price": 2.5,
    "cost": 7.82,
    "stock": 7,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Aretes",
    "images": [],
    "image": null
  },
  {
    "id": 117,
    "name": "Anillos regulables rosados",
    "description": "Anillos regulables rosados",
    "price": 0.8,
    "cost": 4.29,
    "stock": 10,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Anillo",
    "images": [],
    "image": null
  },
  {
    "id": 118,
    "name": "Esferos de gel arcoiris",
    "description": "Esferos de gel arcoiris",
    "price": 1,
    "cost": 4.52,
    "stock": 12,
    "tax": 0,
    "discount": 0,
    "category": "Papeleria",
    "subcategory": "Esferos",
    "images": [],
    "image": null
  },
  {
    "id": 119,
    "name": "Láminas para acné",
    "description": "Láminas para acné",
    "price": 0.5,
    "cost": 2.47,
    "stock": 12,
    "tax": 0,
    "discount": 0,
    "category": "Cuidado de la piel",
    "subcategory": "Acné",
    "images": [],
    "image": null
  },
  {
    "id": 120,
    "name": "Bolso blanco de Nylon Hello Kitty",
    "description": "Bolso blanco de Nylon Hello Kitty",
    "price": 10,
    "cost": 4.67,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 121,
    "name": "Bolso negro grande Hello Kitty",
    "description": "Bolso negro grande Hello Kitty",
    "price": 14,
    "cost": 8.08,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 122,
    "name": "Bandolera negra Hello Kitty",
    "description": "Bandolera negra Hello Kitty",
    "price": 11,
    "cost": 6.15,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 123,
    "name": "Cosmetiquera pequeña rosada Hello Kitty",
    "description": "Cosmetiquera pequeña rosada Hello Kitty",
    "price": 5.5,
    "cost": 2.49,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 124,
    "name": "Bolso de compras Kuromi",
    "description": "Bolso de compras Kuromi",
    "price": 5,
    "cost": 2.9,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 125,
    "name": "Neceser Hello Kitty",
    "description": "Neceser Hello Kitty",
    "price": 3.5,
    "cost": 1.17,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 126,
    "name": "Neceser Kuromi",
    "description": "Neceser Kuromi",
    "price": 3.5,
    "cost": 1.03,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 127,
    "name": "Lonchera térmica a rayas Hello Kitty",
    "description": "Lonchera térmica a rayas Hello Kitty",
    "price": 6,
    "cost": 2.34,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 128,
    "name": "Bolso grande de lona Hello Kitty",
    "description": "Bolso grande de lona Hello Kitty",
    "price": 11,
    "cost": 4.8,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 129,
    "name": "Bolso de lona Hello Kityy",
    "description": "Bolso de lona Hello Kityy",
    "price": 7,
    "cost": 2.23,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 130,
    "name": "Lonchera tèrmica rosada Hello kitty",
    "description": "Lonchera tèrmica rosada Hello kitty",
    "price": 6,
    "cost": 2.07,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 131,
    "name": "Bolso, mochila Hello Kitty",
    "description": "Bolso, mochila Hello Kitty",
    "price": 13,
    "cost": 6.74,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 132,
    "name": "Cosmetiquera grande blanca",
    "description": "Cosmetiquera grande blanca",
    "price": 7,
    "cost": 2.82,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 133,
    "name": "Bolso de lona carita Hello Kitty",
    "description": "Bolso de lona carita Hello Kitty",
    "price": 12,
    "cost": 6.13,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 134,
    "name": "Botiquin de tela Hello Kitty",
    "description": "Botiquin de tela Hello Kitty",
    "price": 5,
    "cost": 1.74,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 135,
    "name": "Reloj rosado niña Hello Kitty",
    "description": "Reloj rosado niña Hello Kitty",
    "price": 8,
    "cost": 4.12,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Reloj",
    "images": [],
    "image": null
  },
  {
    "id": 136,
    "name": "Bolso cafè Hello Kitty",
    "description": "Bolso cafè Hello Kitty",
    "price": 12,
    "cost": 6.21,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 137,
    "name": "Aretes estrella con borla",
    "description": "Aretes estrella con borla",
    "price": 4,
    "cost": 1.83,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Aretes",
    "images": [],
    "image": null
  },
  {
    "id": 138,
    "name": "Aretes luna y estrella",
    "description": "Aretes luna y estrella",
    "price": 3.5,
    "cost": 1.53,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "aretes",
    "images": [],
    "image": null
  },
  {
    "id": 139,
    "name": "Aretes flor blana",
    "description": "Aretes flor blana",
    "price": 4,
    "cost": 1.79,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Aretes",
    "images": [],
    "image": null
  },
  {
    "id": 140,
    "name": "Aretes de gato negro",
    "description": "Aretes de gato negro",
    "price": 5,
    "cost": 1.71,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Aretes",
    "images": [],
    "image": null
  },
  {
    "id": 141,
    "name": "Anillos acero inoxidable nena",
    "description": "Anillos acero inoxidable nena",
    "price": 2.75,
    "cost": 5.03,
    "stock": 5,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Anillos",
    "images": [],
    "image": null
  },
  {
    "id": 142,
    "name": "Anillo de acero inoxidable",
    "description": "Anillo de acero inoxidable",
    "price": 2.75,
    "cost": 3.22,
    "stock": 5,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Anillos",
    "images": [],
    "image": null
  },
  {
    "id": 143,
    "name": "Collar Hello Kitty rojo",
    "description": "Collar Hello Kitty rojo",
    "price": 3.5,
    "cost": 1.15,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Cadena",
    "images": [],
    "image": null
  },
  {
    "id": 144,
    "name": "Juego pandora Hello Kitty",
    "description": "Juego pandora Hello Kitty",
    "price": 7,
    "cost": 3.37,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Cadena",
    "images": [],
    "image": null
  },
  {
    "id": 145,
    "name": "Cadena plateada carita Hello Kitty",
    "description": "Cadena plateada carita Hello Kitty",
    "price": 3.25,
    "cost": 0.69,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Cadena",
    "images": [],
    "image": null
  },
  {
    "id": 146,
    "name": "Aretes corazón",
    "description": "Aretes corazón",
    "price": 3.5,
    "cost": 1.47,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Aretes",
    "images": [],
    "image": null
  },
  {
    "id": 147,
    "name": "Aretes de estrella largos",
    "description": "Aretes de estrella largos",
    "price": 5,
    "cost": 2.7,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Aretes",
    "images": [],
    "image": null
  },
  {
    "id": 148,
    "name": "Pulsera pandora dorada Hello Kitty",
    "description": "Pulsera pandora dorada Hello Kitty",
    "price": 6,
    "cost": 2.88,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Pulsera",
    "images": [],
    "image": null
  },
  {
    "id": 149,
    "name": "Cosmetiquera negra Hello Kitty",
    "description": "Cosmetiquera negra Hello Kitty",
    "price": 6.5,
    "cost": 2.86,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 150,
    "name": "llaveros pequeños Hello Kitty",
    "description": "llaveros pequeños Hello Kitty",
    "price": 1,
    "cost": 1.55,
    "stock": 6,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Llavero",
    "images": [],
    "image": null
  },
  {
    "id": 151,
    "name": "Estuche para labial con espejo",
    "description": "Estuche para labial con espejo",
    "price": 6,
    "cost": 2.63,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 152,
    "name": "Neceser grande Hello Kitty",
    "description": "Neceser grande Hello Kitty",
    "price": 5.5,
    "cost": 2.9,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 153,
    "name": "Cartera de mano Hello Kitty",
    "description": "Cartera de mano Hello Kitty",
    "price": 12,
    "cost": 5.91,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 154,
    "name": "Espejo de mano Hello Kitty",
    "description": "Espejo de mano Hello Kitty",
    "price": 7,
    "cost": 2.76,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Espejo",
    "images": [],
    "image": null
  },
  {
    "id": 155,
    "name": "Billetera larga Hello Kitty",
    "description": "Billetera larga Hello Kitty",
    "price": 7,
    "cost": 3.25,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 156,
    "name": "Billetera pequeña Hello kitty",
    "description": "Billetera pequeña Hello kitty",
    "price": 6,
    "cost": 1.98,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 157,
    "name": "Espeo plegable Hello Kitty",
    "description": "Espeo plegable Hello Kitty",
    "price": 6,
    "cost": 2.14,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Espejo",
    "images": [],
    "image": null
  },
  {
    "id": 158,
    "name": "Monedero Hello Kitty",
    "description": "Monedero Hello Kitty",
    "price": 3.5,
    "cost": 1.16,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 159,
    "name": "Bolso de lona rosado con 2 Hello Kitty",
    "description": "Bolso de lona rosado con 2 Hello Kitty",
    "price": 7,
    "cost": 2.34,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 160,
    "name": "Bandolera Hello Kitty rosada pequeña",
    "description": "Bandolera Hello Kitty rosada pequeña",
    "price": 8,
    "cost": 3.03,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 161,
    "name": "Pulsera elastica Hello Kitty colores",
    "description": "Pulsera elastica Hello Kitty colores",
    "price": 3,
    "cost": 0.96,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Pulsera",
    "images": [],
    "image": null
  },
  {
    "id": 162,
    "name": "Pulsera elastica Hello Kitty blanca",
    "description": "Pulsera elastica Hello Kitty blanca",
    "price": 3,
    "cost": 0.89,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Pulsera",
    "images": [],
    "image": null
  },
  {
    "id": 163,
    "name": "Cosmetiquera plegable rosada Hello Kitty",
    "description": "Cosmetiquera plegable rosada Hello Kitty",
    "price": 10,
    "cost": 4.69,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 164,
    "name": "Cadena dorada cuerpo Hello Kitty",
    "description": "Cadena dorada cuerpo Hello Kitty",
    "price": 4.25,
    "cost": 1.58,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Cadena",
    "images": [],
    "image": null
  },
  {
    "id": 165,
    "name": "Bandolera pequeño rosado Hello Kitty",
    "description": "Bandolera pequeño rosado Hello Kitty",
    "price": 8,
    "cost": 4.68,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 166,
    "name": "Bolso rojo de lona",
    "description": "Bolso rojo de lona",
    "price": 11,
    "cost": 6.58,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 167,
    "name": "Bolso, mochila Hello Kitty",
    "description": "Bolso, mochila Hello Kitty",
    "price": 14,
    "cost": 8.84,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 168,
    "name": "Bolso cruzado rojo Hello Kitty",
    "description": "Bolso cruzado rojo Hello Kitty",
    "price": 12,
    "cost": 7.66,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 169,
    "name": "Bolso cruzado blanco con negro",
    "description": "Bolso cruzado blanco con negro",
    "price": 12,
    "cost": 7.1,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 170,
    "name": "Bolso de Mickey Mouse",
    "description": "Bolso de Mickey Mouse",
    "price": 14,
    "cost": 22.6,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 171,
    "name": "Lapices arcoiris",
    "description": "Lapices arcoiris",
    "price": 0.6,
    "cost": 9.66,
    "stock": 36,
    "tax": 0,
    "discount": 0,
    "category": "Papeleria",
    "subcategory": "Lápiz",
    "images": [],
    "image": null
  },
  {
    "id": 172,
    "name": "Llavero Hello Kitty",
    "description": "Llavero Hello Kitty",
    "price": 1,
    "cost": 1.33,
    "stock": 3,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Llavero",
    "images": [],
    "image": null
  },
  {
    "id": 173,
    "name": "Cepillo de cabello Hello Kitty",
    "description": "Cepillo de cabello Hello Kitty",
    "price": 5,
    "cost": 2.68,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Cepillo",
    "images": [],
    "image": null
  },
  {
    "id": 174,
    "name": "Reloj Sanrio Plateado Hello Kitty",
    "description": "Reloj Sanrio Plateado Hello Kitty",
    "price": 10,
    "cost": 5.2,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Reloj",
    "images": [],
    "image": null
  },
  {
    "id": 175,
    "name": "Collar con nombre",
    "description": "Collar con nombre",
    "price": 6,
    "cost": 2.65,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Cadena",
    "images": [],
    "image": null
  },
  {
    "id": 176,
    "name": "Conjunto de collar más aretes Hello Kitty",
    "description": "Conjunto de collar más aretes Hello Kitty",
    "price": 5,
    "cost": 1.78,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Conjunto",
    "images": [],
    "image": null
  },
  {
    "id": 177,
    "name": "Aretes corazón Hello Kitty",
    "description": "Aretes corazón Hello Kitty",
    "price": 3.5,
    "cost": 1.11,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Aretes",
    "images": [],
    "image": null
  },
  {
    "id": 178,
    "name": "Aretes Hello Kitty cuerpo entero",
    "description": "Aretes Hello Kitty cuerpo entero",
    "price": 3.5,
    "cost": 1.35,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Aretes",
    "images": [],
    "image": null
  },
  {
    "id": 179,
    "name": "Aretes Huevo Frito",
    "description": "Aretes Huevo Frito",
    "price": 3.5,
    "cost": 1.18,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Aretes",
    "images": [],
    "image": null
  },
  {
    "id": 180,
    "name": "Anillo ajustable hoja",
    "description": "Anillo ajustable hoja",
    "price": 2.5,
    "cost": 1.22,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Anillo",
    "images": [],
    "image": null
  },
  {
    "id": 181,
    "name": "Aretes de raton con queso",
    "description": "Aretes de raton con queso",
    "price": 3.5,
    "cost": 1.31,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Aretes",
    "images": [],
    "image": null
  },
  {
    "id": 182,
    "name": "Aretes pequeños Halloween",
    "description": "Aretes pequeños Halloween",
    "price": 1.5,
    "cost": 6.37,
    "stock": 20,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Aretes",
    "images": [],
    "image": null
  },
  {
    "id": 183,
    "name": "Cadena HelloKity plateada cara",
    "description": "Cadena HelloKity plateada cara",
    "price": 3.25,
    "cost": 1.66,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Cadena",
    "images": [],
    "image": null
  },
  {
    "id": 184,
    "name": "Pulsera pandora dorada Hello Kitty",
    "description": "Pulsera pandora dorada Hello Kitty",
    "price": 6,
    "cost": 2.79,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Pulsera",
    "images": [],
    "image": null
  },
  {
    "id": 185,
    "name": "Pulsera elastica Hello Kitty",
    "description": "Pulsera elastica Hello Kitty",
    "price": 3,
    "cost": 0.85,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Pulsera",
    "images": [],
    "image": null
  },
  {
    "id": 186,
    "name": "Reloj Hello Kitty pulsera magnetica",
    "description": "Reloj Hello Kitty pulsera magnetica",
    "price": 10,
    "cost": 4.13,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Reloj",
    "images": [],
    "image": null
  },
  {
    "id": 187,
    "name": "Reloj Hello Kitty blanco",
    "description": "Reloj Hello Kitty blanco",
    "price": 9,
    "cost": 3.73,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Reloj",
    "images": [],
    "image": null
  },
  {
    "id": 188,
    "name": "Juego pandora Hello Kitty",
    "description": "Juego pandora Hello Kitty",
    "price": 7,
    "cost": 3.32,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Conjunto",
    "images": [],
    "image": null
  },
  {
    "id": 189,
    "name": "Juegp cadena con pulsera dorada Hello Kitty",
    "description": "Juegp cadena con pulsera dorada Hello Kitty",
    "price": 5,
    "cost": 2.21,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Conjunto",
    "images": [],
    "image": null
  },
  {
    "id": 190,
    "name": "Diadema Gabyy la casa de  muc;ecas",
    "description": "Diadema Gabyy la casa de  muc;ecas",
    "price": 3.5,
    "cost": 1.46,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Diadema",
    "images": [],
    "image": null
  },
  {
    "id": 191,
    "name": "Colleccion de mu;ecos de Gabby",
    "description": "Colleccion de mu;ecos de Gabby",
    "price": 15,
    "cost": 7.38,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Juguete",
    "subcategory": "mu;ecos",
    "images": [],
    "image": null
  },
  {
    "id": 192,
    "name": "Reloj rosado niña Hello Kitty",
    "description": "Reloj rosado niña Hello Kitty",
    "price": 9,
    "cost": 2.54,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Reloj",
    "images": [],
    "image": null
  },
  {
    "id": 193,
    "name": "Reloj Hello Kitty con lazo",
    "description": "Reloj Hello Kitty con lazo",
    "price": 11,
    "cost": 4.88,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Reloj",
    "images": [],
    "image": null
  },
  {
    "id": 194,
    "name": "Bolso animal print negro Hello Kitty",
    "description": "Bolso animal print negro Hello Kitty",
    "price": 10,
    "cost": 4.72,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 195,
    "name": "Bolso blanco grande con apliques Hello Kitty",
    "description": "Bolso blanco grande con apliques Hello Kitty",
    "price": 15,
    "cost": 6.52,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 196,
    "name": "Bolso Mochila Hello Kitty",
    "description": "Bolso Mochila Hello Kitty",
    "price": 15,
    "cost": 8.04,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 197,
    "name": "Bolso de tela con cosmetiquera Hello Kitty",
    "description": "Bolso de tela con cosmetiquera Hello Kitty",
    "price": 14,
    "cost": 6.61,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 198,
    "name": "Porta labiales con espejo Hello Kitty",
    "description": "Porta labiales con espejo Hello Kitty",
    "price": 7,
    "cost": 3.16,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Portalabiales",
    "images": [],
    "image": null
  },
  {
    "id": 199,
    "name": "Aretes para ni;a",
    "description": "Aretes para ni;a",
    "price": 2,
    "cost": 4.55,
    "stock": 12,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Pendientes",
    "images": [],
    "image": null
  },
  {
    "id": 200,
    "name": "Bolso negro reversible Hello Kitty",
    "description": "Bolso negro reversible Hello Kitty",
    "price": 12,
    "cost": 6.95,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 201,
    "name": "Monedero Pata Daysi",
    "description": "Monedero Pata Daysi",
    "price": 10,
    "cost": 7.05,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 202,
    "name": "Aretes plateados con circonio",
    "description": "Aretes plateados con circonio",
    "price": 3.5,
    "cost": 1.82,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Aretes",
    "images": [],
    "image": null
  },
  {
    "id": 203,
    "name": "Aretes negros",
    "description": "Aretes negros",
    "price": 3.5,
    "cost": 0.95,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Aretes",
    "images": [],
    "image": null
  },
  {
    "id": 204,
    "name": "Reloj Stich",
    "description": "Reloj Stich",
    "price": 9,
    "cost": 3.65,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Reloj",
    "images": [],
    "image": null
  },
  {
    "id": 205,
    "name": "Billetera mine mouse",
    "description": "Billetera mine mouse",
    "price": 10,
    "cost": 5.45,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Billetera",
    "images": [],
    "image": null
  },
  {
    "id": 206,
    "name": "Esferos Hello Kitty",
    "description": "Esferos Hello Kitty",
    "price": 1,
    "cost": 1.78,
    "stock": 6,
    "tax": 0,
    "discount": 0,
    "category": "Papeleria",
    "subcategory": "Esferos",
    "images": [],
    "image": null
  },
  {
    "id": 207,
    "name": "Espejo de maquillaje portatil Hello Kitty",
    "description": "Espejo de maquillaje portatil Hello Kitty",
    "price": 5,
    "cost": 2.44,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Espejo",
    "images": [],
    "image": null
  },
  {
    "id": 208,
    "name": "Billetera larga Hello Kitty blanca",
    "description": "Billetera larga Hello Kitty blanca",
    "price": 7,
    "cost": 3.21,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Billetera",
    "images": [],
    "image": null
  },
  {
    "id": 209,
    "name": "Mini monedero de lujo Hello Kitty",
    "description": "Mini monedero de lujo Hello Kitty",
    "price": 7,
    "cost": 3.47,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Monedero",
    "images": [],
    "image": null
  },
  {
    "id": 210,
    "name": "Monedero Hello Kitty rosado con cierre",
    "description": "Monedero Hello Kitty rosado con cierre",
    "price": 7,
    "cost": 3.11,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Monedero",
    "images": [],
    "image": null
  },
  {
    "id": 211,
    "name": "Bolso delgado y largo Hello Kitty",
    "description": "Bolso delgado y largo Hello Kitty",
    "price": 10,
    "cost": 4.67,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 212,
    "name": "Bandolera rosada Hello Kitty",
    "description": "Bandolera rosada Hello Kitty",
    "price": 15,
    "cost": 7.21,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 213,
    "name": "Monedero rojo Hello Kitty",
    "description": "Monedero rojo Hello Kitty",
    "price": 13,
    "cost": 5.92,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Monedero",
    "images": [],
    "image": null
  },
  {
    "id": 214,
    "name": "Porta labial peque;o con espejo rojo",
    "description": "Porta labial peque;o con espejo rojo",
    "price": 5,
    "cost": 2.21,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Portalabiales",
    "images": [],
    "image": null
  },
  {
    "id": 215,
    "name": "Portla labial, bolso rosado con espejo",
    "description": "Portla labial, bolso rosado con espejo",
    "price": 6,
    "cost": 2.55,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Portalabiales",
    "images": [],
    "image": null
  },
  {
    "id": 216,
    "name": "Estuche para auidifonos Hello Kitty",
    "description": "Estuche para auidifonos Hello Kitty",
    "price": 7,
    "cost": 2.86,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Estuche",
    "images": [],
    "image": null
  },
  {
    "id": 217,
    "name": "Billetera larga negra Hello Kitty",
    "description": "Billetera larga negra Hello Kitty",
    "price": 10,
    "cost": 4,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Billetera",
    "images": [],
    "image": null
  },
  {
    "id": 218,
    "name": "Monedero, porta audifonos Hello Kitty",
    "description": "Monedero, porta audifonos Hello Kitty",
    "price": 6,
    "cost": 1.95,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Monedero",
    "images": [],
    "image": null
  },
  {
    "id": 219,
    "name": "Resaltadores tipo crayon",
    "description": "Resaltadores tipo crayon",
    "price": 1.25,
    "cost": 3.78,
    "stock": 8,
    "tax": 0,
    "discount": 0,
    "category": "Papeleria",
    "subcategory": "Resaltador",
    "images": [],
    "image": null
  },
  {
    "id": 220,
    "name": "Aretes peque;o de gato",
    "description": "Aretes peque;o de gato",
    "price": 2,
    "cost": 1.61,
    "stock": 2,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Pendientes",
    "images": [],
    "image": null
  },
  {
    "id": 221,
    "name": "Reloj blanco Hello Kitty",
    "description": "Reloj blanco Hello Kitty",
    "price": 7,
    "cost": 2.46,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Reloj",
    "images": [],
    "image": null
  },
  {
    "id": 222,
    "name": "Reloj rojo Hello Kitty",
    "description": "Reloj rojo Hello Kitty",
    "price": 9,
    "cost": 3.29,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Reloj",
    "images": [],
    "image": null
  },
  {
    "id": 223,
    "name": "Cepillo de cabello Hello Kitty",
    "description": "Cepillo de cabello Hello Kitty",
    "price": 5,
    "cost": 2.11,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Cepillo",
    "images": [],
    "image": null
  },
  {
    "id": 224,
    "name": "Monedero Hello Kity",
    "description": "Monedero Hello Kity",
    "price": 5,
    "cost": 2.13,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Monedero",
    "images": [],
    "image": null
  },
  {
    "id": 225,
    "name": "Parches para acné trasnparente",
    "description": "Parches para acné trasnparente",
    "price": 0.5,
    "cost": 1.92,
    "stock": 20,
    "tax": 0,
    "discount": 0,
    "category": "Cuidado de la piel",
    "subcategory": "Acné",
    "images": [],
    "image": null
  },
  {
    "id": 226,
    "name": "Cosmetiquera Sanrio Blanca",
    "description": "Cosmetiquera Sanrio Blanca",
    "price": 10,
    "cost": 5.74,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 227,
    "name": "Cosmetiquera rosada Hello Kitty",
    "description": "Cosmetiquera rosada Hello Kitty",
    "price": 9,
    "cost": 4.9,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 228,
    "name": "Cosmetiquera roja Hello Kitty",
    "description": "Cosmetiquera roja Hello Kitty",
    "price": 10,
    "cost": 6.09,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 229,
    "name": "Llaero tipo peluche Hello Kitty",
    "description": "Llaero tipo peluche Hello Kitty",
    "price": 3.5,
    "cost": 1.85,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Llavero",
    "images": [],
    "image": null
  },
  {
    "id": 230,
    "name": "Bolso Blanco con cierre Hello Kitty",
    "description": "Bolso Blanco con cierre Hello Kitty",
    "price": 15,
    "cost": 9.03,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 231,
    "name": "Monedero Hello Kitty",
    "description": "Monedero Hello Kitty",
    "price": 7,
    "cost": 3.65,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Monedero",
    "images": [],
    "image": null
  },
  {
    "id": 232,
    "name": "Billetera con tajetero Hello Kitty",
    "description": "Billetera con tajetero Hello Kitty",
    "price": 9,
    "cost": 4.5,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Billetera",
    "images": [],
    "image": null
  },
  {
    "id": 233,
    "name": "Pulsera calavera",
    "description": "Pulsera calavera",
    "price": 5,
    "cost": 2.3,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Pulsera",
    "images": [],
    "image": null
  },
  {
    "id": 234,
    "name": "Bolso, mochila plateado",
    "description": "Bolso, mochila plateado",
    "price": 17,
    "cost": 10.63,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 235,
    "name": "Mochila negra Hello kitty",
    "description": "Mochila negra Hello kitty",
    "price": 17,
    "cost": 11.6,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Mochila",
    "images": [],
    "image": null
  },
  {
    "id": 236,
    "name": "Mochila flores Hello Kitty",
    "description": "Mochila flores Hello Kitty",
    "price": 15,
    "cost": 8.29,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Mochila",
    "images": [],
    "image": null
  },
  {
    "id": 237,
    "name": "Anillo mariposa acero inoxidable",
    "description": "Anillo mariposa acero inoxidable",
    "price": 2,
    "cost": 2.25,
    "stock": 3,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Anillos",
    "images": [],
    "image": null
  },
  {
    "id": 238,
    "name": "Collar con dije corazon azul",
    "description": "Collar con dije corazon azul",
    "price": 5,
    "cost": 2.55,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Conjunto",
    "images": [],
    "image": null
  },
  {
    "id": 239,
    "name": "Collar con corazon negro",
    "description": "Collar con corazon negro",
    "price": 4,
    "cost": 1.68,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Collar",
    "images": [],
    "image": null
  },
  {
    "id": 240,
    "name": "Conjunto de cadenas plateadas",
    "description": "Conjunto de cadenas plateadas",
    "price": 3,
    "cost": 1.08,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Cadena",
    "images": [],
    "image": null
  },
  {
    "id": 241,
    "name": "conjunto de cadena con aretes corazon negro",
    "description": "conjunto de cadena con aretes corazon negro",
    "price": 4,
    "cost": 1.56,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Conjunto",
    "images": [],
    "image": null
  },
  {
    "id": 242,
    "name": "conjunto de 3 cadenas negras gota",
    "description": "conjunto de 3 cadenas negras gota",
    "price": 4,
    "cost": 1.45,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Conjunto",
    "images": [],
    "image": null
  },
  {
    "id": 243,
    "name": "Aretes de dinosaurio",
    "description": "Aretes de dinosaurio",
    "price": 3.5,
    "cost": 1.31,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "Pendientes",
    "images": [],
    "image": null
  },
  {
    "id": 244,
    "name": "Bolso de hombro Sanrio",
    "description": "Bolso de hombro Sanrio",
    "price": 15,
    "cost": 8.83,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 245,
    "name": "Bolso de Jean",
    "description": "Bolso de Jean",
    "price": 13,
    "cost": 7.99,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 246,
    "name": "Bandolera Hello Kitty",
    "description": "Bandolera Hello Kitty",
    "price": 10,
    "cost": 5.2,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 247,
    "name": "Bolso cruzado rosado Hello Kitty",
    "description": "Bolso cruzado rosado Hello Kitty",
    "price": 10,
    "cost": 5.11,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 248,
    "name": "Cosmetiquera rosada Hello Kitty",
    "description": "Cosmetiquera rosada Hello Kitty",
    "price": 7,
    "cost": 3.08,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 249,
    "name": "Bolso peque;o cruzado negro y concho de vino",
    "description": "Bolso peque;o cruzado negro y concho de vino",
    "price": 13,
    "cost": 6.46,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 250,
    "name": "Bolso cruzado blnaco Hello Kity",
    "description": "Bolso cruzado blnaco Hello Kity",
    "price": 12,
    "cost": 5.42,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 251,
    "name": "Bolso de lona para ni;as Hello Kitty",
    "description": "Bolso de lona para ni;as Hello Kitty",
    "price": 7,
    "cost": 3.33,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 252,
    "name": "Cosmetiquera blanca Hello Kitty",
    "description": "Cosmetiquera blanca Hello Kitty",
    "price": 7,
    "cost": 3.51,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 253,
    "name": "Mochila negra peque;a Hello Kitty",
    "description": "Mochila negra peque;a Hello Kitty",
    "price": 8,
    "cost": 3.91,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Mochila",
    "images": [],
    "image": null
  },
  {
    "id": 254,
    "name": "Mini mochila crauzada para ni;a HK",
    "description": "Mini mochila crauzada para ni;a HK",
    "price": 6,
    "cost": 2.91,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Mochila",
    "images": [],
    "image": null
  },
  {
    "id": 255,
    "name": "Mini Bolso minie para ni;a",
    "description": "Mini Bolso minie para ni;a",
    "price": 6,
    "cost": 2.1,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 256,
    "name": "Bolso de lona Mickey Mouse",
    "description": "Bolso de lona Mickey Mouse",
    "price": 11,
    "cost": 5.38,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 257,
    "name": "Bolso de lona grande Mickey mouse",
    "description": "Bolso de lona grande Mickey mouse",
    "price": 12,
    "cost": 4.99,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 258,
    "name": "Mochila peque;a Mickey mouse",
    "description": "Mochila peque;a Mickey mouse",
    "price": 8,
    "cost": 4.19,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Mochila",
    "images": [],
    "image": null
  },
  {
    "id": 259,
    "name": "Reloj Mickey Mouse",
    "description": "Reloj Mickey Mouse",
    "price": 10,
    "cost": 4.55,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 260,
    "name": "Bolso de lona HK",
    "description": "Bolso de lona HK",
    "price": 12,
    "cost": 4.18,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 261,
    "name": "Bolso de hombro HK",
    "description": "Bolso de hombro HK",
    "price": 10,
    "cost": 4.21,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 262,
    "name": "cartuchera blanca HK",
    "description": "cartuchera blanca HK",
    "price": 6,
    "cost": 2.73,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 263,
    "name": "Monederos transparentes",
    "description": "Monederos transparentes",
    "price": 1.5,
    "cost": 6.63,
    "stock": 10,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Monedero",
    "images": [],
    "image": null
  },
  {
    "id": 264,
    "name": "Resaltadores tipo crayon amarillos",
    "description": "Resaltadores tipo crayon amarillos",
    "price": 1.25,
    "cost": 4.2,
    "stock": 8,
    "tax": 0,
    "discount": 0,
    "category": "Papeleria",
    "subcategory": "Resaltador",
    "images": [],
    "image": null
  },
  {
    "id": 265,
    "name": "Llavero tipo peluche Hello Kitty",
    "description": "Llavero tipo peluche Hello Kitty",
    "price": 3.5,
    "cost": 2.61,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Llavero",
    "images": [],
    "image": null
  },
  {
    "id": 266,
    "name": "Billetera huntrix",
    "description": "Billetera huntrix",
    "price": 8,
    "cost": 4.75,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 267,
    "name": "Llavero giratorio Helllo Kitty",
    "description": "Llavero giratorio Helllo Kitty",
    "price": 5,
    "cost": 2.13,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Llavero",
    "images": [],
    "image": null
  },
  {
    "id": 268,
    "name": "Bolso peluche Hello Kitty",
    "description": "Bolso peluche Hello Kitty",
    "price": 10,
    "cost": 4.32,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 269,
    "name": "Bolso negro",
    "description": "Bolso negro",
    "price": 15,
    "cost": 10.84,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Bolso",
    "images": [],
    "image": null
  },
  {
    "id": 270,
    "name": "Delantal Hello Kitty",
    "description": "Delantal Hello Kitty",
    "price": 7,
    "cost": 3.57,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Delantal",
    "images": [],
    "image": null
  },
  {
    "id": 271,
    "name": "Reloj despertador Hello Kitty",
    "description": "Reloj despertador Hello Kitty",
    "price": 7,
    "cost": 3.39,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Reloj",
    "images": [],
    "image": null
  },
  {
    "id": 272,
    "name": "espoejo Hello Kitty",
    "description": "espoejo Hello Kitty",
    "price": 7,
    "cost": 3.33,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Espejo",
    "images": [],
    "image": null
  },
  {
    "id": 273,
    "name": "Aretes largos Hello Kitty",
    "description": "Aretes largos Hello Kitty",
    "price": 4,
    "cost": 1.68,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Bisuteria",
    "subcategory": "aretes",
    "images": [],
    "image": null
  },
  {
    "id": 274,
    "name": "Resaltadores de gel x6",
    "description": "Resaltadores de gel x6",
    "price": 7,
    "cost": 3.35,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Papeleria",
    "subcategory": "Resaltador",
    "images": [],
    "image": null
  },
  {
    "id": 275,
    "name": "Cordones para telefono",
    "description": "Cordones para telefono",
    "price": 2,
    "cost": 3.54,
    "stock": 5,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Cordones",
    "images": [],
    "image": null
  },
  {
    "id": 276,
    "name": "Correa ajustable para telefono",
    "description": "Correa ajustable para telefono",
    "price": 4,
    "cost": 1.76,
    "stock": 1,
    "tax": 0,
    "discount": 0,
    "category": "Accesorios",
    "subcategory": "Cordones",
    "images": [],
    "image": null
  }
];
